/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 coin.gltf --transform 
Files: coin.gltf [132.82KB] > coin-transformed.glb [257.29KB] (-94%)
Author: suryansh9868 (https://sketchfab.com/suryansh9868)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bitcoin-610f78901aff47b18f44a8b3afd64e38
Title: Bitcoin
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/coin-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[-0.058, 3.088, 1.551]} rotation={[1.534, 0.373, -0.561]} scale={[0.69, 0.497, 0.69]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.PaletteMaterial002} position={[0.672, 1.26, -0.561]} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.PaletteMaterial003} position={[0.672, 1.26, -0.561]} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.PaletteMaterial004} position={[0.142, 1.255, 1.374]} rotation={[Math.PI / 2, 0, 0]} scale={[0.22, 0.733, 0.273]} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.PaletteMaterial005} position={[-0.887, 0.607, 2.301]} rotation={[0.744, -0.826, -0.208]} scale={0.059} />
    </group>
  )
}

useGLTF.preload('/coin-transformed.glb')
