/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 techEngine.gltf --transform 
Files: techEngine.gltf [15.54MB] > techEngine-transformed.glb [1.21MB] (92%)
Author: Renafox (https://sketchfab.com/kryik1023)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/radial-symmetry-test-86e211e4f0a94a63aa731871ec537d97
Title: Radial Symmetry Test
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/techEngine-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Cylinder001_Material_#2_0'].geometry} material={materials.Material_2} position={[0, 0, -0.178]} rotation={[0, -Math.PI / 2, 0]} scale={0.9} />
    </group>
  )
}

useGLTF.preload('/techEngine-transformed.glb')
